// <auto-generated />
using System;
using CairoWeather.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CairoWeather.Data.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    [Migration("20260506082342_AddedTablesAndTMY")]
    partial class AddedTablesAndTMY
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("HourlyReadingSequence");

            modelBuilder.Entity("CairoWeather.Core.Models.HourlyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [HourlyReadingSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<double?>("AirDensity")
                        .HasColumnType("float");

                    b.Property<double?>("ApparentTemperature")
                        .HasColumnType("float");

                    b.Property<double?>("ClearSkyRadiation")
                        .HasColumnType("float");

                    b.Property<double?>("CloudCover")
                        .HasColumnType("float");

                    b.Property<double?>("CloudCoverHigh")
                        .HasColumnType("float");

                    b.Property<double?>("CloudCoverLow")
                        .HasColumnType("float");

                    b.Property<double?>("CloudCoverMid")
                        .HasColumnType("float");

                    b.Property<double?>("CloudRadiativeForcing")
                        .HasColumnType("float");

                    b.Property<double?>("DewPoint2m")
                        .HasColumnType("float");

                    b.Property<double?>("Et0FaoEvapotranspiration")
                        .HasColumnType("float");

                    b.Property<double?>("Humidex")
                        .HasColumnType("float");

                    b.Property<double?>("PhotoThermalUnit")
                        .HasColumnType("float");

                    b.Property<double?>("PressureMsl")
                        .HasColumnType("float");

                    b.Property<double?>("RelativeHumidity2m")
                        .HasColumnType("float");

                    b.Property<double?>("ShortwaveRadiation")
                        .HasColumnType("float");

                    b.Property<double?>("SoilMoisture0To7cm")
                        .HasColumnType("float");

                    b.Property<double?>("SoilMoisture100To255cm")
                        .HasColumnType("float");

                    b.Property<double?>("SoilMoisture28To100cm")
                        .HasColumnType("float");

                    b.Property<double?>("SoilMoisture7To28cm")
                        .HasColumnType("float");

                    b.Property<double?>("SoilTemperature0To7cm")
                        .HasColumnType("float");

                    b.Property<double?>("SoilTemperature100To255cm")
                        .HasColumnType("float");

                    b.Property<double?>("SoilTemperature28To100cm")
                        .HasColumnType("float");

                    b.Property<double?>("SoilTemperature7To28cm")
                        .HasColumnType("float");

                    b.Property<double?>("SurfacePressure")
                        .HasColumnType("float");

                    b.Property<double?>("Temperature2m")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<double?>("VapourPressureDeficit")
                        .HasColumnType("float");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("int");

                    b.Property<double?>("WindDirection100m")
                        .HasColumnType("float");

                    b.Property<double?>("WindDirection10m")
                        .HasColumnType("float");

                    b.Property<double?>("WindGusts10m")
                        .HasColumnType("float");

                    b.Property<double?>("WindPowerDensity")
                        .HasColumnType("float");

                    b.Property<double?>("WindSpeed100m")
                        .HasColumnType("float");

                    b.Property<double?>("WindSpeed10m")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Time")
                        .IsUnique();

                    b.ToTable("HourlyReadings", (string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("CairoWeather.Data.DbContexts.TmyReading", b =>
                {
                    b.HasBaseType("CairoWeather.Core.Models.HourlyReading");

                    b.ToTable("TmyReadings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
