// <auto-generated />
using System;
using CairoWeather.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CairoWeather.Data.Migrations
{
    [DbContext(typeof(EnergyDbContext))]
    partial class EnergyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CairoWeather.Core.Models.DailyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ApparentTemperatureMax")
                        .HasColumnType("float");

                    b.Property<double>("ApparentTemperatureMean")
                        .HasColumnType("float");

                    b.Property<double>("ApparentTemperatureMin")
                        .HasColumnType("float");

                    b.Property<double>("CloudCoverMax")
                        .HasColumnType("float");

                    b.Property<double>("CloudCoverMean")
                        .HasColumnType("float");

                    b.Property<double>("CloudCoverMin")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("DaylightDuration")
                        .HasColumnType("float");

                    b.Property<double>("DewPoint2mMax")
                        .HasColumnType("float");

                    b.Property<double>("DewPoint2mMean")
                        .HasColumnType("float");

                    b.Property<double>("DewPoint2mMin")
                        .HasColumnType("float");

                    b.Property<double>("Et0FaoEvapotranspirationSum")
                        .HasColumnType("float");

                    b.Property<double>("PressureMslMax")
                        .HasColumnType("float");

                    b.Property<double>("PressureMslMean")
                        .HasColumnType("float");

                    b.Property<double>("PressureMslMin")
                        .HasColumnType("float");

                    b.Property<double>("RelativeHumidity2mMax")
                        .HasColumnType("float");

                    b.Property<double>("RelativeHumidity2mMean")
                        .HasColumnType("float");

                    b.Property<double>("RelativeHumidity2mMin")
                        .HasColumnType("float");

                    b.Property<double>("ShortwaveRadiationSum")
                        .HasColumnType("float");

                    b.Property<double>("SnowfallWaterEquivalentSum")
                        .HasColumnType("float");

                    b.Property<double>("SoilMoisture0To100cmMean")
                        .HasColumnType("float");

                    b.Property<double>("SoilMoisture0To7cmMean")
                        .HasColumnType("float");

                    b.Property<double>("SoilMoisture28To100cmMean")
                        .HasColumnType("float");

                    b.Property<double>("SoilMoisture7To28cmMean")
                        .HasColumnType("float");

                    b.Property<double>("SoilTemperature0To100cmMean")
                        .HasColumnType("float");

                    b.Property<double>("SoilTemperature0To7cmMean")
                        .HasColumnType("float");

                    b.Property<double>("SoilTemperature28To100cmMean")
                        .HasColumnType("float");

                    b.Property<double>("SoilTemperature7To28cmMean")
                        .HasColumnType("float");

                    b.Property<string>("Sunrise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sunset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SunshineDuration")
                        .HasColumnType("float");

                    b.Property<double>("SurfacePressureMax")
                        .HasColumnType("float");

                    b.Property<double>("SurfacePressureMean")
                        .HasColumnType("float");

                    b.Property<double>("SurfacePressureMin")
                        .HasColumnType("float");

                    b.Property<double>("Temperature2mMax")
                        .HasColumnType("float");

                    b.Property<double>("Temperature2mMean")
                        .HasColumnType("float");

                    b.Property<double>("Temperature2mMin")
                        .HasColumnType("float");

                    b.Property<double>("VapourPressureDeficitMax")
                        .HasColumnType("float");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("int");

                    b.Property<double>("WetBulbTemperature2mMax")
                        .HasColumnType("float");

                    b.Property<double>("WetBulbTemperature2mMean")
                        .HasColumnType("float");

                    b.Property<double>("WetBulbTemperature2mMin")
                        .HasColumnType("float");

                    b.Property<double>("WindDirection10mDominant")
                        .HasColumnType("float");

                    b.Property<double>("WindGusts10mMax")
                        .HasColumnType("float");

                    b.Property<double>("WindGusts10mMean")
                        .HasColumnType("float");

                    b.Property<double>("WindGusts10mMin")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeed10mMax")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeed10mMean")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeed10mMin")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("DailyReadings");
                });

            modelBuilder.Entity("CairoWeather.Core.Models.HourlyReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ApparentTemperature")
                        .HasColumnType("float");

                    b.Property<double>("CloudCover")
                        .HasColumnType("float");

                    b.Property<double>("CloudCoverHigh")
                        .HasColumnType("float");

                    b.Property<double>("CloudCoverLow")
                        .HasColumnType("float");

                    b.Property<double>("CloudCoverMid")
                        .HasColumnType("float");

                    b.Property<double>("DewPoint2m")
                        .HasColumnType("float");

                    b.Property<double>("Et0FaoEvapotranspiration")
                        .HasColumnType("float");

                    b.Property<double>("PressureMsl")
                        .HasColumnType("float");

                    b.Property<double>("RelativeHumidity2m")
                        .HasColumnType("float");

                    b.Property<double>("SoilMoisture0To7cm")
                        .HasColumnType("float");

                    b.Property<double>("SoilMoisture100To255cm")
                        .HasColumnType("float");

                    b.Property<double>("SoilMoisture28To100cm")
                        .HasColumnType("float");

                    b.Property<double>("SoilMoisture7To28cm")
                        .HasColumnType("float");

                    b.Property<double>("SoilTemperature0To7cm")
                        .HasColumnType("float");

                    b.Property<double>("SoilTemperature100To255cm")
                        .HasColumnType("float");

                    b.Property<double>("SoilTemperature28To100cm")
                        .HasColumnType("float");

                    b.Property<double>("SoilTemperature7To28cm")
                        .HasColumnType("float");

                    b.Property<double>("SurfacePressure")
                        .HasColumnType("float");

                    b.Property<double>("Temperature2m")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<double>("VapourPressureDeficit")
                        .HasColumnType("float");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("int");

                    b.Property<double>("WindDirection100m")
                        .HasColumnType("float");

                    b.Property<double>("WindDirection10m")
                        .HasColumnType("float");

                    b.Property<double>("WindGusts10m")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeed100m")
                        .HasColumnType("float");

                    b.Property<double>("WindSpeed10m")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("HourlyReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
